/**********************************************************************
 *
 *   Component generated by Quest
 *
 *   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts.
 *   To preseve that abilty, always export from Quest to regenerate this file.
 *   To setup props, bindings and actions, use the Quest editor
 *   Code Logic goes in the hook associated with this component
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from 'react';
import HospitalRoom1Image from 'src/assets/images/Slide9_hospital_room_1.png';
import RobotHelpingRemovebgImage from 'src/assets/images/Slide9_Robot_helping_removebg_preview_1.png';
import TextBoxTransparentBaImage from 'src/assets/images/Slide9_text_box_Transparent_Background_1.png';
import Rectangle3Image from 'src/assets/images/Slide9_Rectangle_3.png';
import Menu1Image from 'src/assets/images/Slide9_menu_1.png';
import { styled } from '@mui/material/styles';

const Slide91 = styled('div')({
  backgroundColor: `rgba(255, 255, 255, 1)`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  width: '100%',
  height: `1024px`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  overflow: `hidden`,
});

const HospitalRoom1 = styled('img')({
  height: `1032px`,
  width: `1440px`,
  objectFit: `cover`,
  position: `absolute`,
  left: `0px`,
  top: `-8px`,
});

const Rectangle2 = styled('div')({
  backgroundColor: `rgba(0, 135, 46, 1)`,
  border: `1px solid rgba(0, 0, 0, 1)`,
  boxSizing: `border-box`,
  width: `350px`,
  height: `36px`,
  position: `absolute`,
  left: `793px`,
  top: `728px`,
});

const Rectangle14 = styled('div')({
  backgroundColor: `rgba(0, 135, 46, 1)`,
  border: `1px solid rgba(0, 0, 0, 1)`,
  boxSizing: `border-box`,
  width: `350px`,
  height: `36px`,
  position: `absolute`,
  left: `793px`,
  top: `786px`,
});

const RobotHelpingRemovebg = styled('img')({
  height: `411px`,
  width: `369px`,
  objectFit: `cover`,
  position: `absolute`,
  left: `386px`,
  top: `580px`,
});

const TextBoxTransparentBa = styled('img')({
  height: `449px`,
  width: `516px`,
  objectFit: `cover`,
  position: `absolute`,
  left: `146px`,
  top: `144px`,
});

const TheOtherPeopleInTheW = styled('div')({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Goldman`,
  fontWeight: `700`,
  fontSize: `32px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  textShadow: `0px 4px 4px rgba(0, 0, 0, 0.25)`,
  mixBlendMode: `darken`,
  width: `413px`,
  height: `196px`,
  position: `absolute`,
  left: `197px`,
  top: `198px`,
});

const Rectangle3 = styled('img')({
  height: `36px`,
  width: `350px`,
  position: `absolute`,
  left: `793px`,
  top: `656px`,
});

const WomanSittingOnTheCou = styled('div')({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Goldman`,
  fontWeight: `700`,
  fontSize: `16px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `339px`,
  height: `50px`,
  position: `absolute`,
  left: `804px`,
  top: `736px`,
});

const TheReceptionistSitti = styled('div')({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Goldman`,
  fontWeight: `700`,
  fontSize: `16px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `339px`,
  height: `50px`,
  position: `absolute`,
  left: `798px`,
  top: `790px`,
});

const Rectangle4 = styled('div')({
  backgroundColor: `rgba(217, 217, 217, 1)`,
  mixBlendMode: `color-burn`,
  width: `342px`,
  height: `193px`,
  position: `absolute`,
  left: `872px`,
  top: `131px`,
});

const Rectangle5 = styled('div')({
  backgroundColor: `rgba(103, 255, 127, 1)`,
  mixBlendMode: `color-dodge`,
  width: `280px`,
  height: `30px`,
  position: `absolute`,
  left: `793px`,
  top: `540px`,
});

const ChooseAnOption = styled('div')({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Goldman`,
  fontWeight: `700`,
  fontSize: `24px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `283px`,
  height: `40px`,
  position: `absolute`,
  left: `790px`,
  top: `540px`,
});

const ManBehindYouLookingA = styled('div')({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Goldman`,
  fontWeight: `700`,
  fontSize: `16px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `350px`,
  height: `48px`,
  position: `absolute`,
  left: `793px`,
  top: `660px`,
});

const Menu1 = styled('img')({
  height: `145px`,
  width: `146px`,
  objectFit: `cover`,
  position: `absolute`,
  left: `1270px`,
  top: `19px`,
});

const Rectangle13 = styled('div')({
  backgroundColor: `rgba(0, 0, 0, 1)`,
  mixBlendMode: `lighten`,
  width: `197px`,
  height: `174px`,
  position: `absolute`,
  left: `1243px`,
  top: `0px`,
});

function Slide9(props) {
  return (
    <Slide91 className={props.className}>
      <HospitalRoom1
        src={HospitalRoom1Image}
        loading="lazy"
        alt={'hospital room 1'}
      />
      <Rectangle2></Rectangle2>
      <Rectangle14></Rectangle14>
      <RobotHelpingRemovebg
        src={RobotHelpingRemovebgImage}
        loading="lazy"
        alt={'Robot_helping-removebg-preview 1'}
      />
      <TextBoxTransparentBa
        src={TextBoxTransparentBaImage}
        loading="lazy"
        alt={'text_box_Transparent_Background 1'}
      />
      <TheOtherPeopleInTheW>
        {`The other people in the waiting room shouldn’t see what password you chose, but some people look suspicious.
Who saw your password?`}
      </TheOtherPeopleInTheW>
      <Rectangle3 src={Rectangle3Image} loading="lazy" alt={'Rectangle 3'} />
      <WomanSittingOnTheCou>
        {`Woman sitting on the couch`}
      </WomanSittingOnTheCou>
      <TheReceptionistSitti>
        {`The receptionist sitting at the counter`}
      </TheReceptionistSitti>
      <Rectangle4></Rectangle4>
      <Rectangle5></Rectangle5>
      <ChooseAnOption>{`CHOOSE AN OPTION`}</ChooseAnOption>
      <ManBehindYouLookingA>
        {`Man behind you looking at your screen `}
      </ManBehindYouLookingA>
      <Menu1 src={Menu1Image} loading="lazy" alt={'menu 1'} />
      <Rectangle13></Rectangle13>
    </Slide91>
  );
}

export default Slide9;
