/**********************************************************************
 *
 *   Component generated by Quest
 *
 *   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts.
 *   To preseve that abilty, always export from Quest to regenerate this file.
 *   To setup props, bindings and actions, use the Quest editor
 *   Code Logic goes in the hook associated with this component
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from 'react';
import HospitalRoom1Image from 'src/assets/images/Slide10_hospital_room_1.png';
import RobotHelpingRemovebgImage from 'src/assets/images/Slide10_Robot_helping_removebg_preview_1.png';
import TextBoxTransparentBaImage from 'src/assets/images/Slide10_text_box_Transparent_Background_1.png';
import Rectangle3Image from 'src/assets/images/Slide10_Rectangle_3.png';
import Menu1Image from 'src/assets/images/Slide10_menu_1.png';
import FloatingRobotRemovebImage from 'src/assets/images/Slide10_floating_robot_removebg_preview_2.png';
import TextboxRemovebgPreviImage from 'src/assets/images/Slide10_textbox_removebg_preview_2.png';
import { styled } from '@mui/material/styles';

const Slide101 = styled('div')({
  backgroundColor: `rgba(255, 255, 255, 1)`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  width: '100%',
  height: `1024px`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  overflow: `hidden`,
});

const HospitalRoom1 = styled('img')({
  height: `1032px`,
  width: `1440px`,
  objectFit: `cover`,
  position: `absolute`,
  left: `0px`,
  top: `-8px`,
});

const Rectangle2 = styled('div')({
  backgroundColor: `rgba(0, 135, 46, 1)`,
  border: `1px solid rgba(0, 0, 0, 1)`,
  boxSizing: `border-box`,
  width: `350px`,
  height: `36px`,
  position: `absolute`,
  left: `793px`,
  top: `718px`,
});

const Rectangle14 = styled('div')({
  backgroundColor: `rgba(0, 135, 46, 1)`,
  border: `1px solid rgba(0, 0, 0, 1)`,
  boxSizing: `border-box`,
  width: `350px`,
  height: `36px`,
  position: `absolute`,
  left: `795px`,
  top: `781px`,
});

const Rectangle15 = styled('div')({
  backgroundColor: `rgba(0, 135, 46, 1)`,
  border: `1px solid rgba(0, 0, 0, 1)`,
  boxSizing: `border-box`,
  width: `350px`,
  height: `36px`,
  position: `absolute`,
  left: `793px`,
  top: `848px`,
});

const RobotHelpingRemovebg = styled('img')({
  height: `411px`,
  width: `369px`,
  objectFit: `cover`,
  position: `absolute`,
  left: `386px`,
  top: `580px`,
});

const TextBoxTransparentBa = styled('img')({
  height: `477px`,
  width: `541px`,
  objectFit: `cover`,
  position: `absolute`,
  left: `138px`,
  top: `153px`,
});

const TheHackerHasAccessTo = styled('div')({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Goldman`,
  fontWeight: `700`,
  fontSize: `28px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  textShadow: `0px 4px 4px rgba(0, 0, 0, 0.25)`,
  mixBlendMode: `darken`,
  width: `413px`,
  height: `196px`,
  position: `absolute`,
  left: `202px`,
  top: `205px`,
});

const Rectangle3 = styled('img')({
  height: `228px`,
  width: `350px`,
  position: `absolute`,
  left: `793px`,
  top: `653px`,
});

const HttpW6LVerylegitLink = styled('div')({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Goldman`,
  fontWeight: `700`,
  fontSize: `16px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `339px`,
  height: `58px`,
  position: `absolute`,
  left: `806px`,
  top: `716px`,
});

const RixlinkWazer1385Spee = styled('div')({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Goldman`,
  fontWeight: `700`,
  fontSize: `16px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `339px`,
  height: `50px`,
  position: `absolute`,
  left: `798px`,
  top: `779px`,
});

const HttpPuswurdmannayere = styled('div')({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Goldman`,
  fontWeight: `700`,
  fontSize: `16px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `339px`,
  height: `50px`,
  position: `absolute`,
  left: `795px`,
  top: `848px`,
});

const Rectangle4 = styled('div')({
  backgroundColor: `rgba(217, 217, 217, 1)`,
  mixBlendMode: `color-burn`,
  width: `342px`,
  height: `193px`,
  position: `absolute`,
  left: `872px`,
  top: `131px`,
});

const Rectangle5 = styled('div')({
  backgroundColor: `rgba(103, 255, 127, 1)`,
  mixBlendMode: `color-dodge`,
  width: `280px`,
  height: `30px`,
  position: `absolute`,
  left: `793px`,
  top: `540px`,
});

const ChooseTheSafeLink = styled('div')({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Goldman`,
  fontWeight: `700`,
  fontSize: `20px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `291px`,
  height: `55px`,
  position: `absolute`,
  left: `790px`,
  top: `540px`,
});

const HttpsWwwPasswordmana = styled('div')({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Goldman`,
  fontWeight: `700`,
  fontSize: `16px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `350px`,
  height: `48px`,
  position: `absolute`,
  left: `793px`,
  top: `658px`,
});

const Menu1 = styled('img')({
  height: `145px`,
  width: `146px`,
  objectFit: `cover`,
  position: `absolute`,
  left: `1270px`,
  top: `19px`,
});

const Rectangle13 = styled('div')({
  backgroundColor: `rgba(0, 0, 0, 1)`,
  mixBlendMode: `lighten`,
  width: `197px`,
  height: `174px`,
  position: `absolute`,
  left: `1243px`,
  top: `0px`,
});

const FloatingRobotRemoveb = styled('img')({
  height: `323px`,
  width: `317px`,
  position: `absolute`,
  left: `1224px`,
  top: `261px`,
});

const TextboxRemovebgPrevi = styled('img')({
  height: `192px`,
  width: `680px`,
  objectFit: `cover`,
  position: `absolute`,
  left: `2088px`,
  top: `453px`,
});

const APasswordManagerCanH = styled('div')({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Goldman`,
  fontWeight: `700`,
  fontSize: `24px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `336px`,
  height: `126px`,
  position: `absolute`,
  left: `888px`,
  top: `291px`,
});

function Slide10(props) {
  return (
    <Slide101 className={props.className}>
      <HospitalRoom1
        src={HospitalRoom1Image}
        loading="lazy"
        alt={'hospital room 1'}
      />
      <Rectangle2></Rectangle2>
      <Rectangle14></Rectangle14>
      <Rectangle15></Rectangle15>
      <RobotHelpingRemovebg
        src={RobotHelpingRemovebgImage}
        loading="lazy"
        alt={'Robot_helping-removebg-preview 1'}
      />
      <TextBoxTransparentBa
        src={TextBoxTransparentBaImage}
        loading="lazy"
        alt={'text_box_Transparent_Background 1'}
      />
      <TheHackerHasAccessTo>
        {`The hacker has access to all your accounts, including your e-mail! You made the mistake of using the same password for multiple accounts... Choose a link to download a password manager from.`}
      </TheHackerHasAccessTo>
      <Rectangle3 src={Rectangle3Image} loading="lazy" alt={'Rectangle 3'} />
      <HttpW6LVerylegitLink>
        {`Http://w6l.verylegit-link10xwzU;*trojanvirus`}
      </HttpW6LVerylegitLink>
      <RixlinkWazer1385Spee>
        {`Rixlink/wazer1385speedupvcpc.gif.pdf.dmg`}
      </RixlinkWazer1385Spee>
      <HttpPuswurdmannayere>
        {`Http://puswurdmannayere:al/donlod`}
      </HttpPuswurdmannayere>
      <Rectangle4></Rectangle4>
      <Rectangle5></Rectangle5>
      <ChooseTheSafeLink>{`CHOOSE THE SAFE LINK`}</ChooseTheSafeLink>
      <HttpsWwwPasswordmana>
        {`Https://www.passwordmanager.com/download`}
      </HttpsWwwPasswordmana>
      <Menu1 src={Menu1Image} loading="lazy" alt={'menu 1'} />
      <Rectangle13></Rectangle13>
      <FloatingRobotRemoveb
        src={FloatingRobotRemovebImage}
        loading="lazy"
        alt={'floating_robot-removebg-preview 2'}
      />
      <TextboxRemovebgPrevi
        src={TextboxRemovebgPreviImage}
        loading="lazy"
        alt={'textbox-removebg-preview 2'}
      />
      <APasswordManagerCanH>
        {`A password manager can help you save passwords securely and help you remember them.`}
      </APasswordManagerCanH>
    </Slide101>
  );
}

export default Slide10;
