/**********************************************************************
 *
 *   Component generated by Quest
 *
 *   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts.
 *   To preseve that abilty, always export from Quest to regenerate this file.
 *   To setup props, bindings and actions, use the Quest editor
 *   Code Logic goes in the hook associated with this component
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from 'react';
import HospitalRoom1Image from 'src/assets/images/Slide3_hospital_room_1.png';
import Menu3Image from 'src/assets/images/Slide3_menu_3.png';
import LaptopScreen1Image from 'src/assets/images/Slide3_laptop_screen_1.png';
import Image5Image from 'src/assets/images/Slide3_image_5.png';
import Rectangle20Image from 'src/assets/images/Slide3_Rectangle_20.png';
import Rectangle21Image from 'src/assets/images/Slide3_Rectangle_21.png';
import Rectangle22Image from 'src/assets/images/Slide3_Rectangle_22.png';
import Rectangle23Image from 'src/assets/images/Slide3_Rectangle_23.png';
import { styled } from '@mui/material/styles';
import TextBoxTransparentBaImage from 'src/assets/images/Slide3_text_box_Transparent_Background_1.png';

const Slide31 = styled('div')({
  backgroundColor: `rgba(255, 255, 255, 1)`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  width: '100%',
  height: `1024px`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  overflow: `hidden`,
});

const HospitalRoom1 = styled('img')({
  height: `1032px`,
  width: `1440px`,
  objectFit: `cover`,
  position: `absolute`,
  left: `0px`,
  top: `-8px`,
});

const Rectangle12 = styled('div')({
  backgroundColor: `rgba(0, 0, 0, 1)`,
  mixBlendMode: `lighten`,
  width: `197px`,
  height: `174px`,
  position: `absolute`,
  left: `1243px`,
  top: `0px`,
});

const Rectangle13 = styled('div')({
  backgroundColor: `rgba(0, 0, 0, 1)`,
  mixBlendMode: `lighten`,
  width: `197px`,
  height: `174px`,
  position: `absolute`,
  left: `1240px`,
  top: `0px`,
});

const Menu3 = styled('img')({
  height: `145px`,
  width: `146px`,
  objectFit: `cover`,
  position: `absolute`,
  left: `1269px`,
  top: `3px`,
});

const Rectangle14 = styled('div')({
  width: `382px`,
  height: `220px`,
  position: `absolute`,
  left: `834px`,
  top: `12px`,
});

const LaptopScreen1 = styled('img')({
  height: `645px`,
  width: `860px`,
  position: `absolute`,
  left: `266px`,
  top: `264px`,
});

const Rectangle15 = styled('div')({
  backgroundColor: `rgba(0, 135, 46, 1)`,
  width: `842px`,
  height: `451px`,
  position: `absolute`,
  left: `276px`,
  top: `277px`,
});

const PickAPassword = styled('div')({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `Goldman`,
  fontWeight: `700`,
  fontSize: `32px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  position: `absolute`,
  left: `536px`,
  top: `332px`,
});

const Image5 = styled('img')({
  height: `204px`,
  width: `204px`,
  objectFit: `cover`,
  position: `absolute`,
  left: `851px`,
  top: `406px`,
});

const TextBoxTransparentBa = styled('div')({
  backgroundImage: `url(${TextBoxTransparentBaImage})`,
  backgroundPosition: `center`,
  backgroundSize: `cover`,
  backgroundRepeat: `no-repeat`,
  width: `414.74px`,
  height: `361px`,
  position: `absolute`,
  left: `780px`,
  top: `29px`,
});

const OkNowWhatPasswordSho = styled('div')({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Goldman`,
  fontWeight: `700`,
  fontSize: `28.148147583007812px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `378px`,
  height: `196px`,
  position: `absolute`,
  left: `810px`,
  top: `120px`,
});

const ABCD = styled('div')({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `Goldman`,
  fontWeight: `700`,
  fontSize: `24px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  position: `absolute`,
  left: `311px`,
  top: `436px`,
});

const Rectangle20 = styled('img')({
  height: `42px`,
  width: `134px`,
  position: `absolute`,
  left: `349px`,
  top: `429px`,
});

const Rectangle21 = styled('img')({
  height: `34px`,
  width: `228px`,
  position: `absolute`,
  left: `349px`,
  top: `493px`,
});

const Rectangle22 = styled('img')({
  height: `34px`,
  width: `214px`,
  position: `absolute`,
  left: `350px`,
  top: `546px`,
});

const Rectangle23 = styled('img')({
  height: `34px`,
  width: `214px`,
  position: `absolute`,
  left: `349px`,
  top: `605px`,
});

const Qwerty123 = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Courier Prime`,
  fontWeight: `700`,
  fontSize: `24px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  position: `absolute`,
  left: `353px`,
  top: `438px`,
});

const SKszVg2VmH4 = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Courier Prime`,
  fontWeight: `700`,
  fontSize: `24px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  position: `absolute`,
  left: `357px`,
  top: `497px`,
});

const Username2023 = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Courier Prime`,
  fontWeight: `700`,
  fontSize: `24px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  position: `absolute`,
  left: `357px`,
  top: `550px`,
});

const Administrator = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Courier Prime`,
  fontWeight: `700`,
  fontSize: `24px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  position: `absolute`,
  left: `360px`,
  top: `610px`,
});

function Slide3(props) {
  return (
    <Slide31 className={props.className}>
      <HospitalRoom1
        src={HospitalRoom1Image}
        loading="lazy"
        alt={'hospital room 1'}
      />
      <Rectangle12></Rectangle12>
      <Rectangle13></Rectangle13>
      <Menu3 src={Menu3Image} loading="lazy" alt={'menu 3'} />
      <Rectangle14></Rectangle14>
      <LaptopScreen1
        src={LaptopScreen1Image}
        loading="lazy"
        alt={'laptop screen 1'}
      />
      <Rectangle15></Rectangle15>
      <PickAPassword>{`Pick a password!`}</PickAPassword>
      <Image5 src={Image5Image} loading="lazy" alt={'image 5'} />
      <TextBoxTransparentBa></TextBoxTransparentBa>
      <OkNowWhatPasswordSho>
        {`Ok now,
What password should
I pick...`}
      </OkNowWhatPasswordSho>
      <ABCD>
        {`A.

B.

C.

D.`}
      </ABCD>
      <Rectangle20 src={Rectangle20Image} loading="lazy" alt={'Rectangle 20'} />
      <Rectangle21 src={Rectangle21Image} loading="lazy" alt={'Rectangle 21'} />
      <Rectangle22 src={Rectangle22Image} loading="lazy" alt={'Rectangle 22'} />
      <Rectangle23 src={Rectangle23Image} loading="lazy" alt={'Rectangle 23'} />
      <Qwerty123>{`qwerty123`}</Qwerty123>
      <SKszVg2VmH4>{`sKszVg@!2Vm#_H4`}</SKszVg2VmH4>
      <Username2023>{`<username>2023`}</Username2023>
      <Administrator>{`administrator`}</Administrator>
    </Slide31>
  );
}

export default Slide3;
