/**********************************************************************
 *
 *   Component generated by Quest
 *
 *   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts.
 *   To preseve that abilty, always export from Quest to regenerate this file.
 *   To setup props, bindings and actions, use the Quest editor
 *   Code Logic goes in the hook associated with this component
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from 'react';
import HospitalRoom1Image from 'src/assets/images/Slide8_hospital_room_1.png';
import Menu3Image from 'src/assets/images/Slide8_menu_3.png';
import LaptopScreen1Image from 'src/assets/images/Slide8_laptop_screen_1.png';
import { styled } from '@mui/material/styles';
import TextBoxTransparentBaImage from 'src/assets/images/Slide8_text_box_Transparent_Background_1.png';

const Slide81 = styled('div')({
  backgroundColor: `rgba(255, 255, 255, 1)`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  width: '100%',
  height: `1024px`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  overflow: `hidden`,
});

const HospitalRoom1 = styled('img')({
  height: `1032px`,
  width: `1440px`,
  objectFit: `cover`,
  position: `absolute`,
  left: `0px`,
  top: `-8px`,
});

const TextBoxTransparentBa = styled('div')({
  backgroundImage: `url(${TextBoxTransparentBaImage})`,
  backgroundPosition: `center`,
  backgroundSize: `cover`,
  backgroundRepeat: `no-repeat`,
  width: `342px`,
  height: `298px`,
  position: `absolute`,
  left: `0px`,
  top: `406px`,
});

const Rectangle12 = styled('div')({
  backgroundColor: `rgba(0, 0, 0, 1)`,
  mixBlendMode: `lighten`,
  width: `197px`,
  height: `174px`,
  position: `absolute`,
  left: `1243px`,
  top: `0px`,
});

const Rectangle13 = styled('div')({
  backgroundColor: `rgba(0, 0, 0, 1)`,
  mixBlendMode: `lighten`,
  width: `197px`,
  height: `174px`,
  position: `absolute`,
  left: `1240px`,
  top: `0px`,
});

const Menu3 = styled('img')({
  height: `145px`,
  width: `146px`,
  objectFit: `cover`,
  position: `absolute`,
  left: `1269px`,
  top: `3px`,
});

const Rectangle14 = styled('div')({
  width: `382px`,
  height: `220px`,
  position: `absolute`,
  left: `834px`,
  top: `12px`,
});

const LaptopScreen1 = styled('img')({
  height: `467px`,
  width: `635px`,
  position: `absolute`,
  left: `390px`,
  top: `406px`,
});

const Rectangle15 = styled('div')({
  backgroundColor: `rgba(0, 135, 46, 1)`,
  width: `623px`,
  height: `323px`,
  position: `absolute`,
  left: `398px`,
  top: `415px`,
});

const Rectangle24 = styled('div')({
  backgroundColor: `rgba(217, 217, 217, 1)`,
  width: `270px`,
  height: `61px`,
  position: `absolute`,
  left: `579px`,
  top: `624px`,
});

const TryAgainLater = styled('div')({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Goldman`,
  fontWeight: `700`,
  fontSize: `32px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  position: `absolute`,
  left: `585px`,
  top: `636px`,
});

const WhyCanTILogBackInDid = styled('div')({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Goldman`,
  fontWeight: `700`,
  fontSize: `32px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  textShadow: `0px 4px 4px rgba(0, 0, 0, 0.25)`,
  mixBlendMode: `darken`,
  width: `262px`,
  height: `147px`,
  position: `absolute`,
  left: `40px`,
  top: `456px`,
});

const ThereIsAProblemLoggi = styled('div')({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Goldman`,
  fontWeight: `700`,
  fontSize: `32px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  textShadow: `0px 4px 4px rgba(0, 0, 0, 0.25)`,
  mixBlendMode: `darken`,
  width: `431px`,
  height: `147px`,
  position: `absolute`,
  left: `517px`,
  top: `485px`,
});

const Error404 = styled('div')({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Goldman`,
  fontWeight: `400`,
  fontSize: `28px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  textShadow: `0px 4px 4px rgba(0, 0, 0, 0.25)`,
  mixBlendMode: `darken`,
  width: `232px`,
  height: `90px`,
  position: `absolute`,
  left: `385px`,
  top: `424px`,
});

function Slide8(props) {
  return (
    <Slide81 className={props.className}>
      <HospitalRoom1
        src={HospitalRoom1Image}
        loading="lazy"
        alt={'hospital room 1'}
      />
      <TextBoxTransparentBa></TextBoxTransparentBa>
      <Rectangle12></Rectangle12>
      <Rectangle13></Rectangle13>
      <Menu3 src={Menu3Image} loading="lazy" alt={'menu 3'} />
      <Rectangle14></Rectangle14>
      <LaptopScreen1
        src={LaptopScreen1Image}
        loading="lazy"
        alt={'laptop screen 1'}
      />
      <Rectangle15></Rectangle15>
      <Rectangle24></Rectangle24>
      <TryAgainLater>{`Try again later`}</TryAgainLater>
      <WhyCanTILogBackInDid>
        {`Why can’t I log back in?
Did I get hacked!?`}
      </WhyCanTILogBackInDid>
      <ThereIsAProblemLoggi>
        {`There is a problem logging you back in...`}
      </ThereIsAProblemLoggi>
      <Error404>{`error 404:`}</Error404>
    </Slide81>
  );
}

export default Slide8;
