/**********************************************************************
 *
 *   Component generated by Quest
 *
 *   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts.
 *   To preseve that abilty, always export from Quest to regenerate this file.
 *   To setup props, bindings and actions, use the Quest editor
 *   Code Logic goes in the hook associated with this component
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from 'react';
import HospitalRoom1Image from 'src/assets/images/Slide2_hospital_room_1.png';
import Menu3Image from 'src/assets/images/Slide2_menu_3.png';
import LaptopScreen1Image from 'src/assets/images/Slide2_laptop_screen_1.png';
import Rectangle20Image from 'src/assets/images/Slide2_Rectangle_20.png';
import Rectangle21Image from 'src/assets/images/Slide2_Rectangle_21.png';
import Image5Image from 'src/assets/images/Slide2_image_5.png';
import Image6Image from 'src/assets/images/Slide2_image_6.png';
import { styled } from '@mui/material/styles';
import { Input } from '@mui/material';
import { useNavigate } from 'react-router-dom';
import TextBoxTransparentBaImage from 'src/assets/images/Slide2_text_box_Transparent_Background_1.png';



const Slide21 = styled('div')({
  backgroundColor: `rgba(255, 255, 255, 1)`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  width: '100%',
  height: `1024px`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  overflow: `hidden`,
});

const HospitalRoom1 = styled('img')({
  height: `1032px`,
  width: `1440px`,
  objectFit: `cover`,
  position: `absolute`,
  left: `0px`,
  top: `-8px`,
});

const Rectangle12 = styled('div')({
  backgroundColor: `rgba(0, 0, 0, 1)`,
  mixBlendMode: `lighten`,
  width: `197px`,
  height: `174px`,
  position: `absolute`,
  left: `1243px`,
  top: `0px`,
});

const Rectangle13 = styled('div')({
  backgroundColor: `rgba(0, 0, 0, 1)`,
  mixBlendMode: `lighten`,
  width: `197px`,
  height: `174px`,
  position: `absolute`,
  left: `1240px`,
  top: `0px`,
});

const Menu3 = styled('img')({
  height: `145px`,
  width: `146px`,
  objectFit: `cover`,
  position: `absolute`,
  left: `1269px`,
  top: `3px`,
});

const Rectangle14 = styled('div')({
  width: `382px`,
  height: `220px`,
  position: `absolute`,
  left: `834px`,
  top: `12px`,
});

const LaptopScreen1 = styled('img')({
  height: `645px`,
  width: `860px`,
  position: `absolute`,
  left: `266px`,
  top: `264px`,
});

const Rectangle15 = styled('div')({
  backgroundColor: `rgba(0, 135, 46, 1)`,
  width: `842px`,
  height: `451px`,
  position: `absolute`,
  left: `276px`,
  top: `277px`,
});

const EnterAUsernameInTheB = styled('div')({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `Goldman`,
  fontWeight: `700`,
  fontSize: `32px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  position: `absolute`,
  left: `380px`,
  top: `332px`,
});

const Rectangle20 = styled('img')({
  height: `50px`,
  width: `55px`,
  position: `absolute`,
  left: `815px`,
  top: `655px`,
});

const Rectangle21 = styled('input')({
  height: `44px`,
  width: `265px`,
  position: `absolute`,
  left: `525px`,
  top: `656px`,
  fontSize: '16px',
});

const EnterAUsername = styled('div')({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Courier Prime`,
  fontWeight: `400`,
  fontSize: `32px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  position: `absolute`,
  left: `535px`,
  top: `614px`,
});

const Frame2 = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  width: `100px`,
  height: `100px`,
  left: `658px`,
  top: `323px`,
  overflow: `hidden`,
});

const Image5 = styled('img')({
  height: `204px`,
  width: `204px`,
  objectFit: `cover`,
  position: `absolute`,
  left: `586px`,
  top: `400px`,
});

const TextBoxTransparentBa = styled('div')({
  backgroundImage: `url(${TextBoxTransparentBaImage})`,
  backgroundPosition: `center`,
  backgroundSize: `cover`,
  backgroundRepeat: `no-repeat`,
  width: `414.74px`,
  height: `361px`,
  position: `absolute`,
  left: `780px`,
  top: `29px`,
});

const HmmWhatUsernameShoul = styled('div')({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Goldman`,
  fontWeight: `700`,
  fontSize: `28.148147583007812px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `378px`,
  height: `196px`,
  position: `absolute`,
  left: `810px`,
  top: `120px`,
});

const Image6 = styled('img')({
  height: `32px`,
  width: `32px`,
  objectFit: `cover`,
  position: `absolute`,
  left: `826px`,
  top: `664px`,
});

function Slide2(props) {
  const navigate = useNavigate();
  const handleButtonClick = () => {
    navigate('/slide3');
  };
  return (
    <Slide21 className={props.className}>
      <HospitalRoom1
        src={HospitalRoom1Image}
        loading="lazy"
        alt={'hospital room 1'}
      />
      <Rectangle12></Rectangle12>
      <Rectangle13></Rectangle13>
      <Menu3 src={Menu3Image} loading="lazy" alt={'menu 3'} />
      <Rectangle14></Rectangle14>
      <LaptopScreen1
        src={LaptopScreen1Image}
        loading="lazy"
        alt={'laptop screen 1'}
      />
      <Rectangle15></Rectangle15>
      <EnterAUsernameInTheB>
        {`Enter a username in the box below!`}
      </EnterAUsernameInTheB>
      <Rectangle20 onClick={handleButtonClick} src={Rectangle20Image} loading="lazy" alt={'Rectangle 20'} />
      <Rectangle21 loading="lazy" alt={'Rectangle 21'}/>
      <Input/>
      <EnterAUsername>{`Enter a username`}</EnterAUsername>
      <Frame2>
    </Frame2>
      <Image5 src={Image5Image} loading="lazy" alt={'image 5'} />
      <TextBoxTransparentBa></TextBoxTransparentBa>
      <HmmWhatUsernameShoul>
        {`Hmm...
What username should
I pick...`}
      </HmmWhatUsernameShoul>
      <Image6 onClick={handleButtonClick} src={Image6Image} loading="lazy" alt={'image 6'} />
    </Slide21>
  );
}

export default Slide2;
