/**********************************************************************
 *
 *   Component generated by Quest
 *
 *   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts.
 *   To preseve that abilty, always export from Quest to regenerate this file.
 *   To setup props, bindings and actions, use the Quest editor
 *   Code Logic goes in the hook associated with this component
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from 'react';
import Hospital1Image from 'src/assets/images/Start_hospital_1.png';
import FloatingRobotRemovebImage from 'src/assets/images/Start_floating_robot_removebg_preview_1.png';
import Rectangle6Image from 'src/assets/images/Start_Rectangle_6.png';
import { useNavigate } from 'react-router-dom';
import Rectangle19Image from 'src/assets/images/Start_Rectangle_19.png';
import Rectangle20Image from 'src/assets/images/Start_Rectangle_20.png';
import { styled } from '@mui/material/styles';
import RobotSayingHiRemovebImage from 'src/assets/images/Start_Robot_saying_hi_removebg_preview_1.png';

const Start1 = styled('div')({
  backgroundColor: `rgba(255, 255, 255, 1)`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  width: '100%',
  height: `1024px`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  overflow: `hidden`,
});

const Rectangle4 = styled('div')({
  backgroundColor: `rgba(217, 217, 217, 1)`,
  mixBlendMode: `color-burn`,
  width: `342px`,
  height: `193px`,
  position: `absolute`,
  left: `872px`,
  top: `131px`,
});

const Hospital1 = styled('img')({
  height: `1024px`,
  width: `1440px`,
  objectFit: `cover`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const FloatingRobotRemoveb = styled('img')({
  height: `250px`,
  width: `261px`,
  position: `absolute`,
  left: `469px`,
  top: `227px`,
});

const Rectangle6 = styled('img')({
  height: `276px`,
  width: `786px`,
  position: `absolute`,
  left: `327px`,
  top: `304px`,
});

const HackerCatcher = styled('div')({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Goldman`,
  fontWeight: `700`,
  fontSize: `128px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  position: `absolute`,
  left: `451px`,
  top: `289px`,
});

const RobotSayingHiRemoveb = styled('div')({
  backgroundImage: `url(${RobotSayingHiRemovebImage})`,
  backgroundPosition: `center`,
  backgroundSize: `cover`,
  backgroundRepeat: `no-repeat`,
  width: `693px`,
  height: `675px`,
  position: `absolute`,
  left: `-90px`,
  top: `381px`,
});

const Frame1 = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  width: `100px`,
  height: `100px`,
  left: `658px`,
  top: `146px`,
  overflow: `hidden`,
});

const Rectangle19 = styled('img')({
  height: `123px`,
  width: `366px`,
  position: `absolute`,
  left: `506px`,
  top: `611px`,
  cursor: 'pointer',
  transition: 'color 0.3s ease', /* Add transition for color change */

    '&:hover': {
      color: '#000000', /* Change the color on hover */
    },
});

const Play = styled('div')({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Goldman`,
  cursor: 'pointer',
  fontWeight: `700`,
  fontSize: `80px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `20px`,
  textTransform: `none`,
  position: `absolute`,
  left: `567px`,
  top: `663px`,
});

const Rectangle20 = styled('img')({
  height: `176px`,
  width: `366px`,
  position: `absolute`,
  left: `506px`,
  top: `777px`,
});

const LoadGame = styled('div')({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Goldman`,
  fontWeight: `700`,
  fontSize: `80px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `60px`,
  textTransform: `none`,
  position: `absolute`,
  left: `550px`,
  top: `811px`,
});

function Start(props) {
  const navigate = useNavigate();
  const handleButtonClick = () => {
    navigate('/slide1');
  };

  return (
    <Start1 className={props.className}>
      <Rectangle4></Rectangle4>
      <Hospital1 src={Hospital1Image} loading="lazy" alt={'hospital 1'} />
      <FloatingRobotRemoveb
        src={FloatingRobotRemovebImage}
        loading="lazy"
        alt={'floating_robot-removebg-preview 1'}
      />
      <Rectangle6 src={Rectangle6Image} loading="lazy" alt={'Rectangle 6'} />
      <HackerCatcher>
        {`Hacker 
Catcher`}
      </HackerCatcher>
      <RobotSayingHiRemoveb></RobotSayingHiRemoveb>
      <Frame1></Frame1>
      <Rectangle19 src={Rectangle19Image} onClick={handleButtonClick} loading="lazy"  alt={'Rectangle 19'} />
        <Play onClick={handleButtonClick}>{`PLAY`}</Play>
      <Rectangle20 src={Rectangle20Image} loading="lazy" alt={'Rectangle 20'} />
      <LoadGame>
        {`LOAD 
GAME`}
      </LoadGame>
    </Start1>
  );
}

export default Start;
